version: '3.4'

services:
  dev:
    image: rentx-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    env_file: .env
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - $PWD:/home/user/app
    working_dir: /home/user/app
    networks:
      - dev_network
    depends_on:
      - pg
  pg:
    image: postgres:13.3-alpine
    container_name: pg_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=mastersecret
      - POSTGRES_DB=rentx
    volumes:
      - /var/run/docker-pg/$PWD:/var/lib/postgresql/data
    networks:
      - dev_network
networks:
  dev_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.103.0.0/16
