version: '3.4'

services:
  01firstprojectwithnodejs:
    image: 01firstprojectwithnodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
    volumes:
      - $PWD:/home/user/app
    working_dir: /home/user/app
    networks:
      - fundamentals_network
networks:
  fundamentals_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.102.0.0/16
